### ISSUE TITLE
How to import into react project?

### ISSUE THREAD

**Issue by jaguardo** [yodahuang/react-nav2djs#3]
I successfully added the node globally, but can't seem to get the module "found" in the project:
```
Module not found: Can't resolve 'react-nav2djs' in
```
I've added it in the project:
```
import NAV2D from 'react-nav2djs'
```

**Comment by yodahuang** [comment]
First, by adding globally, are you inferring you are doing `npm install -g`? To import a module in a project, you just do `npm install` and make sure it is added to the `package.json` file.
Second, it shall be `import Nav2d from "react-nav2djs";`

I tested locally with a simple `create-react-app`. And it works as expected.

**Comment by jaguardo** [comment]
Sure, thanks! Might have been the trick.
